//
// Copyright (c) 2020 Miguel Ángel Ortuño.
// See the LICENSE file for more information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.13.0
// source: stravaganza.proto

package stravaganza

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PBAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PBAttribute) Reset() {
	*x = PBAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stravaganza_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBAttribute) ProtoMessage() {}

func (x *PBAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_stravaganza_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBAttribute.ProtoReflect.Descriptor instead.
func (*PBAttribute) Descriptor() ([]byte, []int) {
	return file_stravaganza_proto_rawDescGZIP(), []int{0}
}

func (x *PBAttribute) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PBAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PBElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attributes []*PBAttribute `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Elements   []*PBElement   `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
	Text       string         `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *PBElement) Reset() {
	*x = PBElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stravaganza_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBElement) ProtoMessage() {}

func (x *PBElement) ProtoReflect() protoreflect.Message {
	mi := &file_stravaganza_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBElement.ProtoReflect.Descriptor instead.
func (*PBElement) Descriptor() ([]byte, []int) {
	return file_stravaganza_proto_rawDescGZIP(), []int{1}
}

func (x *PBElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PBElement) GetAttributes() []*PBAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *PBElement) GetElements() []*PBElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *PBElement) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_stravaganza_proto protoreflect.FileDescriptor

var file_stravaganza_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x72, 0x61, 0x76, 0x61, 0x67, 0x61, 0x6e, 0x7a, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x74, 0x72, 0x61, 0x76, 0x61, 0x67, 0x61, 0x6e, 0x7a, 0x61,
	0x22, 0x39, 0x0a, 0x0b, 0x50, 0x42, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x09,
	0x50, 0x42, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x76, 0x61, 0x67, 0x61, 0x6e, 0x7a, 0x61, 0x2e,
	0x50, 0x42, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x72, 0x61,
	0x76, 0x61, 0x67, 0x61, 0x6e, 0x7a, 0x61, 0x2e, 0x50, 0x42, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61,
	0x63, 0x6b, 0x61, 0x6c, 0x2d, 0x78, 0x6d, 0x70, 0x70, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x76, 0x61,
	0x67, 0x61, 0x6e, 0x7a, 0x61, 0x3b, 0x73, 0x74, 0x72, 0x61, 0x76, 0x61, 0x67, 0x61, 0x6e, 0x7a,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stravaganza_proto_rawDescOnce sync.Once
	file_stravaganza_proto_rawDescData = file_stravaganza_proto_rawDesc
)

func file_stravaganza_proto_rawDescGZIP() []byte {
	file_stravaganza_proto_rawDescOnce.Do(func() {
		file_stravaganza_proto_rawDescData = protoimpl.X.CompressGZIP(file_stravaganza_proto_rawDescData)
	})
	return file_stravaganza_proto_rawDescData
}

var file_stravaganza_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stravaganza_proto_goTypes = []interface{}{
	(*PBAttribute)(nil), // 0: stravaganza.PBAttribute
	(*PBElement)(nil),   // 1: stravaganza.PBElement
}
var file_stravaganza_proto_depIdxs = []int32{
	0, // 0: stravaganza.PBElement.attributes:type_name -> stravaganza.PBAttribute
	1, // 1: stravaganza.PBElement.elements:type_name -> stravaganza.PBElement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stravaganza_proto_init() }
func file_stravaganza_proto_init() {
	if File_stravaganza_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stravaganza_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stravaganza_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stravaganza_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stravaganza_proto_goTypes,
		DependencyIndexes: file_stravaganza_proto_depIdxs,
		MessageInfos:      file_stravaganza_proto_msgTypes,
	}.Build()
	File_stravaganza_proto = out.File
	file_stravaganza_proto_rawDesc = nil
	file_stravaganza_proto_goTypes = nil
	file_stravaganza_proto_depIdxs = nil
}
